---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[yumrepo_server::default]
    attributes:
  - name: custom_port
    run_list:
      - recipe[yumrepo_server::default]
    attributes:
      yum:
        server:
          http_port: 9090
